# Generated by Django 4.2.6 on 2023-11-20 19:37

import apps.core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RequestSnack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=150, verbose_name='Nome do aluno')),
                ('student_registration', models.CharField(max_length=150, verbose_name='Matrícula do aluno')),
                ('data', models.DateField(verbose_name='Data')),
                ('justification', models.TextField(max_length=300, verbose_name='Justificativa')),
                ('status', models.BooleanField(default=False, verbose_name='Situação')),
                ('type', models.CharField(choices=[('almoço', 'almoço'), ('janta', 'janta')], max_length=15, verbose_name='Tipo')),
            ],
        ),
        migrations.CreateModel(
            name='Snack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(max_length=255, verbose_name='Descrição')),
                ('likes', models.IntegerField(default=0, verbose_name='Curtidas')),
                ('image', models.ImageField(null=True, upload_to=apps.core.models.get_file_path, verbose_name='Imagem')),
                ('snack_to_day', models.BooleanField(default=False, verbose_name='Refeição do dia')),
                ('type', models.CharField(choices=[('almoço', 'almoço'), ('janta', 'janta')], max_length=15, verbose_name='Tipo')),
                ('active', models.BooleanField(default=True, verbose_name='Ativo')),
            ],
        ),
    ]
