# Generated by Django 4.2.6 on 2023-11-27 20:02

import apps.core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestSnack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=150, verbose_name='Nome do aluno')),
                ('student_registration', models.CharField(max_length=150, verbose_name='Matrícula do aluno')),
                ('data', models.DateField(verbose_name='Data')),
                ('justification', models.TextField(max_length=300, verbose_name='Justificativa')),
                ('status', models.BooleanField(blank=True, default=False, null=True, verbose_name='Situação')),
                ('type', models.CharField(choices=[('almoço', 'almoço'), ('janta', 'janta')], max_length=15, verbose_name='Tipo')),
            ],
            options={
                'verbose_name': 'Solicitação de Refeição',
            },
        ),
        migrations.CreateModel(
            name='Snack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(max_length=255, verbose_name='Descrição')),
                ('likes', models.IntegerField(blank=True, default=0, null=True, verbose_name='Curtidas')),
                ('image', models.ImageField(null=True, upload_to=apps.core.models.get_file_path, verbose_name='Imagem')),
                ('snack_to_day', models.BooleanField(default=False, verbose_name='Refeição do dia')),
                ('type', models.CharField(choices=[('almoço', 'almoço'), ('janta', 'janta')], max_length=15, verbose_name='Tipo')),
                ('active', models.BooleanField(blank=True, default=True, null=True, verbose_name='Ativo')),
            ],
            options={
                'verbose_name': 'Refeição',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('username', models.CharField(max_length=25, unique=True)),
                ('first_name', models.CharField(max_length=40)),
                ('last_name', models.CharField(max_length=140)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('chef', models.BooleanField(default=False)),
                ('coordenator', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Usuário',
            },
        ),
    ]
