# Generated by Django 4.2.6 on 2023-11-24 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestsnack',
            name='status',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Situação'),
        ),
    ]
