# Generated by Django 4.2.6 on 2023-11-27 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestsnack',
            name='student_name',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Nome do aluno'),
        ),
        migrations.AlterField(
            model_name='requestsnack',
            name='student_registration',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Matrícula do aluno'),
        ),
    ]
