# Generated by Django 4.2.6 on 2023-11-24 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_requestsnack_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestsnack',
            name='data',
            field=models.DateField(auto_now=True, verbose_name='Data'),
        ),
    ]
