# Generated by Django 4.2.6 on 2023-11-24 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_requestsnack_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestsnack',
            name='data',
            field=models.DateField(verbose_name='Data'),
        ),
    ]
