# Generated by Django 4.2.6 on 2023-12-02 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_requestsnack_student_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestsnack',
            name='status',
            field=models.BooleanField(blank=True, choices=[('aprovado', 'aprovado'), ('reprovado', 'reprovado'), ('pendente', 'pendente')], default='pendente', null=True, verbose_name='Situação'),
        ),
    ]
