# Generated by Django 4.2.6 on 2023-11-24 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_requestsnack_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snack',
            name='active',
            field=models.BooleanField(blank=True, default=True, null=True, verbose_name='Ativo'),
        ),
    ]
