# Generated by Django 4.2.6 on 2023-12-02 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_requestsnack_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestsnack',
            name='checked',
            field=models.BooleanField(default=False, verbose_name='Verificado'),
        ),
    ]
