# Generated by Django 4.2.6 on 2023-11-24 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_snack_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snack',
            name='likes',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Curtidas'),
        ),
    ]
