# Generated by Django 4.2.6 on 2023-12-02 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_requestsnack_checked'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestsnack',
            name='student_email',
            field=models.EmailField(blank=True, max_length=150, null=True, verbose_name='Email'),
        ),
    ]
