# Generated by Django 4.2.6 on 2023-12-04 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_snack_likes'),
        ('core', '0007_requestsnack_student_email'),
    ]

    operations = [
    ]
