# Generated by Django 4.2.6 on 2023-12-06 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_merge_20231204_1311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestsnack',
            name='checked',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Verificado'),
        ),
        migrations.AlterField(
            model_name='requestsnack',
            name='status',
            field=models.CharField(blank=True, choices=[('aprovado', 'aprovado'), ('reprovado', 'reprovado'), ('pendente', 'pendente')], default='pendente', max_length=15, null=True, verbose_name='Situação'),
        ),
    ]
