# Generated by Django 4.2.6 on 2023-12-12 13:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_requestsnack_checked_alter_requestsnack_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requestsnack',
            name='student_email',
        ),
        migrations.RemoveField(
            model_name='requestsnack',
            name='student_name',
        ),
        migrations.RemoveField(
            model_name='requestsnack',
            name='student_registration',
        ),
        migrations.AddField(
            model_name='requestsnack',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário'),
        ),
    ]
