# Generated by Django 4.2.6 on 2023-12-12 17:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_remove_requestsnack_student_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestsnack',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário'),
        ),
    ]
