# Generated by Django 4.2.6 on 2023-12-12 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_remove_requestsnack_student_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestsnack',
            name='checked',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Verificado'),
        ),
    ]
