# Generated by Django 4.2.6 on 2023-12-12 22:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_requestsnack_checked'),
        ('core', '0011_alter_requestsnack_user'),
    ]

    operations = [
    ]
